version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: my_frontend_app
    expose:
      - "3000"  # no external access
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: my_backend_app
    expose:
      - "5000"  # no external access
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: my_proxy_app
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  db_data: